// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MpzK7L48lqKcMqBd3suCKRTswOxZtwU',
    appId: '1:21157069349:web:002441ae850fbf3bb175cc',
    messagingSenderId: '21157069349',
    projectId: 'edittomagazine',
    authDomain: 'edittomagazine.firebaseapp.com',
    storageBucket: 'edittomagazine.firebasestorage.app',
    measurementId: 'G-YKXSQ7PBEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYemv-R-6h1XZ5B8ixXxxsfNylEbr4Pak',
    appId: '1:21157069349:android:8d35ef867fc271a1b175cc',
    messagingSenderId: '21157069349',
    projectId: 'edittomagazine',
    storageBucket: 'edittomagazine.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2MpzK7L48lqKcMqBd3suCKRTswOxZtwU',
    appId: '1:21157069349:web:509ef9cb5dcb74fbb175cc',
    messagingSenderId: '21157069349',
    projectId: 'edittomagazine',
    authDomain: 'edittomagazine.firebaseapp.com',
    storageBucket: 'edittomagazine.firebasestorage.app',
    measurementId: 'G-FKSYHTMZDQ',
  );
}
